### Consultar contactos
GET http://127.0.0.1:8000/api/app/contactos

### Crear un nuevo contacto
POST http://127.0.0.1:8000/api/app/contacto
Content-Type: "application/json"

{
    "nombre": "Anita",
    "email": "anita@test.com",
    "telefono": "9988877"
}

### Consultar un contacto por id
GET http://127.0.0.1:8000/api/app/contacto/9

### Modificar un contacto
PUT http://127.0.0.1:8000/api/app/contacto/90
Content-Type: "application/json"

{
    "nombre": "Anita",
    "email": "anita@test.com",
    "telefono": "369852"
}

### Eliminar contacto
DELETE http://127.0.0.1:8000/api/app/contacto/9